sudo: required

services:
  - docker

language: bash

# prepare qemu
before_install:
- docker run --rm --privileged multiarch/qemu-user-static:register --register
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"

# build image
script:
- docker build --build-arg ARCH=$(TARGET) --no-cache -t tmptag -f Dockerfile.armhf .

# push image
after_success:
- >
  if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "armhf"; else echo "$TRAVIS_BRANCH-armhf" ; fi)
    docker tag tmptag $DOCKER_USER/$DOCKER_REPO:$TAG
    docker push $DOCKER_USER/$DOCKER_REPO:$TAG
  fi
